workspace '../CGFloatType.xcworkspace'

target 'CGFloatTypeTests' do
  pod 'CGFloatType', :path => '../'

  pod 'Expecta'
  pod 'Specta'
end

begin
  require 'slather'
  Slather.prepare_pods(self)
rescue LoadError
  UI.warn('Slather has been disabled (not installed).')
end

